# Generated by Django 4.2.3 on 2023-07-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=50)),
                ('que', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
