# Generated by Django 4.2.3 on 2023-07-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_qid_answer_qid11'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='qid11',
            new_name='queid',
        ),
    ]
