# Generated by Django 4.2.3 on 2023-07-28 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_remove_answer_like_answer_liked_alter_answer_queid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
